import type { Internship } from '../types/internship';

// ─── Mock Internship Dataset ──────────────────────────────────────────────────
// 24 internships covering:
//   • Profiles: Web Dev, Data Science, Marketing, Design, Finance, ML, Android, Content
//   • Locations: Delhi, Mumbai, Bangalore, Hyderabad, Chennai, Pune, Noida + WFH
//   • Durations: 1, 2, 3, 6 months
//   • Stipends: Unpaid → ₹25,000
//   • Flags: PPO, Premium, Part-time, WFH, Actively hiring

function makeStipend(value: number): Internship['stipend'] {
  if (value === 0) return { salary: 'Unpaid', salaryValue1: 0, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' };
  const k = value >= 1000 ? `${value / 1000}K` : value;
  return { salary: `₹ ${value.toLocaleString('en-IN')} /month`, salaryValue1: value, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' };
}

function makeStatus(active: boolean): Internship['application_status_message'] {
  return { to_show: active, message: 'Actively hiring', type: 'actively_hiring' };
}

export const MOCK_INTERNSHIPS: Internship[] = [
  {
    id: 1001,
    title: 'Web Development Intern',
    company_name: 'Razorpay',
    company_url: '/company/razorpay',
    company_logo: '',
    is_premium: true,
    is_ppo: true,
    work_from_home: false,
    profile_name: 'Web Development',
    part_time: false,
    start_date: 'Immediately',
    duration: '3 Months',
    stipend: makeStipend(25000),
    posted_on: '1 day ago',
    application_deadline: '15 Jun',
    expiring_in: '1 day ago',
    location_names: ['Bangalore'],
    url: 'web-development-intern-razorpay-1001',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1002,
    title: 'Data Science Intern',
    company_name: 'Flipkart',
    company_url: '/company/flipkart',
    company_logo: '',
    is_premium: false,
    is_ppo: true,
    work_from_home: true,
    profile_name: 'Data Science',
    part_time: false,
    start_date: '1 Jun',
    duration: '6 Months',
    stipend: makeStipend(20000),
    posted_on: '2 days ago',
    application_deadline: '20 Jun',
    expiring_in: '2 days ago',
    location_names: [],
    url: 'data-science-intern-flipkart-1002',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1003,
    title: 'Digital Marketing Intern',
    company_name: 'Nykaa',
    company_url: '/company/nykaa',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Marketing',
    part_time: false,
    start_date: 'Immediately',
    duration: '2 Months',
    stipend: makeStipend(8000),
    posted_on: '3 days ago',
    application_deadline: '10 Jun',
    expiring_in: '3 days ago',
    location_names: ['Mumbai'],
    url: 'digital-marketing-intern-nykaa-1003',
    is_active: false,
    application_status_message: makeStatus(false),
  },
  {
    id: 1004,
    title: 'Machine Learning Intern',
    company_name: 'Ola',
    company_url: '/company/ola',
    company_logo: '',
    is_premium: true,
    is_ppo: false,
    work_from_home: true,
    profile_name: 'Machine Learning',
    part_time: false,
    start_date: '15 Jun',
    duration: '6 Months',
    stipend: makeStipend(18000),
    posted_on: '1 day ago',
    application_deadline: '5 Jun',
    expiring_in: '1 day ago',
    location_names: [],
    url: 'machine-learning-intern-ola-1004',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1005,
    title: 'UI/UX Design Intern',
    company_name: 'Swiggy',
    company_url: '/company/swiggy',
    company_logo: '',
    is_premium: false,
    is_ppo: true,
    work_from_home: false,
    profile_name: 'Graphic Design',
    part_time: false,
    start_date: 'Immediately',
    duration: '3 Months',
    stipend: makeStipend(12000),
    posted_on: '4 days ago',
    application_deadline: '12 Jun',
    expiring_in: '4 days ago',
    location_names: ['Bangalore'],
    url: 'ui-ux-design-intern-swiggy-1005',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1006,
    title: 'Android Development Intern',
    company_name: 'PhonePe',
    company_url: '/company/phonepe',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Android Development',
    part_time: false,
    start_date: '1 Jul',
    duration: '3 Months',
    stipend: makeStipend(15000),
    posted_on: '5 days ago',
    application_deadline: '18 Jun',
    expiring_in: '5 days ago',
    location_names: ['Pune'],
    url: 'android-development-intern-phonepe-1006',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1007,
    title: 'Finance & Accounts Intern',
    company_name: 'Zerodha',
    company_url: '/company/zerodha',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: true,
    profile_name: 'Finance',
    part_time: true,
    start_date: 'Immediately',
    duration: '2 Months',
    stipend: makeStipend(5000),
    posted_on: '6 days ago',
    application_deadline: '8 Jun',
    expiring_in: '6 days ago',
    location_names: [],
    url: 'finance-accounts-intern-zerodha-1007',
    is_active: false,
    application_status_message: makeStatus(false),
  },
  {
    id: 1008,
    title: 'Content Writing Intern',
    company_name: 'Byju\'s',
    company_url: '/company/byjus',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: true,
    profile_name: 'Content Writing',
    part_time: true,
    start_date: 'Immediately',
    duration: '1 Month',
    stipend: makeStipend(0),
    posted_on: '1 week ago',
    application_deadline: '30 Jun',
    expiring_in: '1 week ago',
    location_names: [],
    url: 'content-writing-intern-byjus-1008',
    is_active: false,
    application_status_message: makeStatus(false),
  },
  {
    id: 1009,
    title: 'Full Stack Developer Intern',
    company_name: 'Meesho',
    company_url: '/company/meesho',
    company_logo: '',
    is_premium: true,
    is_ppo: true,
    work_from_home: false,
    profile_name: 'Web Development',
    part_time: false,
    start_date: 'Immediately',
    duration: '6 Months',
    stipend: makeStipend(22000),
    posted_on: '2 days ago',
    application_deadline: '22 Jun',
    expiring_in: '2 days ago',
    location_names: ['Bangalore'],
    url: 'full-stack-developer-intern-meesho-1009',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1010,
    title: 'Business Development Intern',
    company_name: 'FlatX',
    company_url: '/company/flatx',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Business Development',
    part_time: false,
    start_date: 'Immediately',
    duration: '2 Months',
    stipend: makeStipend(10200),
    posted_on: '1 day ago',
    application_deadline: '25 Jun',
    expiring_in: '1 day ago',
    location_names: ['Bangalore'],
    url: 'business-development-intern-flatx-1010',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1011,
    title: 'Data Analytics Intern',
    company_name: 'Paytm',
    company_url: '/company/paytm',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Data Science',
    part_time: false,
    start_date: '15 Jun',
    duration: '3 Months',
    stipend: makeStipend(12000),
    posted_on: '3 days ago',
    application_deadline: '14 Jun',
    expiring_in: '3 days ago',
    location_names: ['Noida'],
    url: 'data-analytics-intern-paytm-1011',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1012,
    title: 'React Developer Intern',
    company_name: 'CRED',
    company_url: '/company/cred',
    company_logo: '',
    is_premium: true,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Web Development',
    part_time: false,
    start_date: '1 Jun',
    duration: '3 Months',
    stipend: makeStipend(20000),
    posted_on: '2 days ago',
    application_deadline: '16 Jun',
    expiring_in: '2 days ago',
    location_names: ['Bangalore'],
    url: 'react-developer-intern-cred-1012',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1013,
    title: 'Social Media Marketing Intern',
    company_name: 'Mamaearth',
    company_url: '/company/mamaearth',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: true,
    profile_name: 'Marketing',
    part_time: true,
    start_date: 'Immediately',
    duration: '2 Months',
    stipend: makeStipend(5000),
    posted_on: '4 days ago',
    application_deadline: '28 Jun',
    expiring_in: '4 days ago',
    location_names: [],
    url: 'social-media-marketing-intern-mamaearth-1013',
    is_active: false,
    application_status_message: makeStatus(false),
  },
  {
    id: 1014,
    title: 'Human Resources Intern',
    company_name: 'Zomato',
    company_url: '/company/zomato',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Human Resources',
    part_time: false,
    start_date: 'Immediately',
    duration: '1 Month',
    stipend: makeStipend(6000),
    posted_on: '5 days ago',
    application_deadline: '9 Jun',
    expiring_in: '5 days ago',
    location_names: ['Delhi'],
    url: 'human-resources-intern-zomato-1014',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1015,
    title: 'Python Development Intern',
    company_name: 'Groww',
    company_url: '/company/groww',
    company_logo: '',
    is_premium: false,
    is_ppo: true,
    work_from_home: true,
    profile_name: 'Web Development',
    part_time: false,
    start_date: '1 Jun',
    duration: '6 Months',
    stipend: makeStipend(15000),
    posted_on: '1 day ago',
    application_deadline: '30 Jun',
    expiring_in: '1 day ago',
    location_names: [],
    url: 'python-development-intern-groww-1015',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1016,
    title: 'Graphic Design Intern',
    company_name: 'boAt',
    company_url: '/company/boat',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Graphic Design',
    part_time: false,
    start_date: 'Immediately',
    duration: '2 Months',
    stipend: makeStipend(7000),
    posted_on: '6 days ago',
    application_deadline: '7 Jun',
    expiring_in: '6 days ago',
    location_names: ['Delhi'],
    url: 'graphic-design-intern-boat-1016',
    is_active: false,
    application_status_message: makeStatus(false),
  },
  {
    id: 1017,
    title: 'iOS Development Intern',
    company_name: 'InMobi',
    company_url: '/company/inmobi',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Android Development',
    part_time: false,
    start_date: '15 Jun',
    duration: '3 Months',
    stipend: makeStipend(18000),
    posted_on: '3 days ago',
    application_deadline: '20 Jun',
    expiring_in: '3 days ago',
    location_names: ['Bangalore'],
    url: 'ios-development-intern-inmobi-1017',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1018,
    title: 'Inside Sales Intern',
    company_name: 'HiWi Forex',
    company_url: '/company/hiwi',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: true,
    profile_name: 'Business Development',
    part_time: false,
    start_date: 'Immediately',
    duration: '6 Months',
    stipend: makeStipend(9000),
    posted_on: '3 days ago',
    application_deadline: '25 Jun',
    expiring_in: '3 days ago',
    location_names: ['Mumbai'],
    url: 'inside-sales-intern-hiwi-1018',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1019,
    title: 'Machine Learning Research Intern',
    company_name: 'Samsung R&D',
    company_url: '/company/samsung-rnd',
    company_logo: '',
    is_premium: true,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Machine Learning',
    part_time: false,
    start_date: '1 Jul',
    duration: '6 Months',
    stipend: makeStipend(25000),
    posted_on: '1 day ago',
    application_deadline: '15 Jun',
    expiring_in: '1 day ago',
    location_names: ['Hyderabad'],
    url: 'ml-research-intern-samsung-1019',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1020,
    title: 'Finance Analyst Intern',
    company_name: 'Angel One',
    company_url: '/company/angel-one',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Finance',
    part_time: false,
    start_date: 'Immediately',
    duration: '3 Months',
    stipend: makeStipend(10000),
    posted_on: '4 days ago',
    application_deadline: '18 Jun',
    expiring_in: '4 days ago',
    location_names: ['Mumbai'],
    url: 'finance-analyst-intern-angelone-1020',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1021,
    title: 'Backend Engineering Intern',
    company_name: 'Juspay',
    company_url: '/company/juspay',
    company_logo: '',
    is_premium: false,
    is_ppo: true,
    work_from_home: false,
    profile_name: 'Web Development',
    part_time: false,
    start_date: '1 Jun',
    duration: '6 Months',
    stipend: makeStipend(20000),
    posted_on: '2 days ago',
    application_deadline: '21 Jun',
    expiring_in: '2 days ago',
    location_names: ['Chennai'],
    url: 'backend-engineering-intern-juspay-1021',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1022,
    title: 'Content Strategy Intern',
    company_name: 'Unacademy',
    company_url: '/company/unacademy',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: true,
    profile_name: 'Content Writing',
    part_time: true,
    start_date: 'Immediately',
    duration: '1 Month',
    stipend: makeStipend(3000),
    posted_on: '1 week ago',
    application_deadline: '28 Jun',
    expiring_in: '1 week ago',
    location_names: [],
    url: 'content-strategy-intern-unacademy-1022',
    is_active: false,
    application_status_message: makeStatus(false),
  },
  {
    id: 1023,
    title: 'DevOps Engineering Intern',
    company_name: 'Postman',
    company_url: '/company/postman',
    company_logo: '',
    is_premium: true,
    is_ppo: true,
    work_from_home: false,
    profile_name: 'Web Development',
    part_time: false,
    start_date: '15 Jun',
    duration: '6 Months',
    stipend: makeStipend(22000),
    posted_on: '1 day ago',
    application_deadline: '10 Jun',
    expiring_in: '1 day ago',
    location_names: ['Bangalore'],
    url: 'devops-engineering-intern-postman-1023',
    is_active: true,
    application_status_message: makeStatus(true),
  },
  {
    id: 1024,
    title: 'Product Management Intern',
    company_name: 'Browserstack',
    company_url: '/company/browserstack',
    company_logo: '',
    is_premium: false,
    is_ppo: false,
    work_from_home: false,
    profile_name: 'Business Development',
    part_time: false,
    start_date: 'Immediately',
    duration: '3 Months',
    stipend: makeStipend(15000),
    posted_on: '3 days ago',
    application_deadline: '22 Jun',
    expiring_in: '3 days ago',
    location_names: ['Mumbai'],
    url: 'product-management-intern-browserstack-1024',
    is_active: false,
    application_status_message: makeStatus(false),
  },
];
